// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYvUxeV9iWv_bpfjcZlODIU0HlK-6AS0o',
    appId: '1:84678725081:web:efa39254f083b949879dc8',
    messagingSenderId: '84678725081',
    projectId: 'news-app-ca3a8',
    authDomain: 'news-app-ca3a8.firebaseapp.com',
    storageBucket: 'news-app-ca3a8.appspot.com',
    measurementId: 'G-EMEHXP47Z1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhB8nOP3-MXz3sDtsiODNLgqXq0KQ2T48',
    appId: '1:84678725081:android:880f24f1e50030a7879dc8',
    messagingSenderId: '84678725081',
    projectId: 'news-app-ca3a8',
    storageBucket: 'news-app-ca3a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0OveRe2g_pdcoSXv_LyKqm-7KWAnZyLs',
    appId: '1:84678725081:ios:b692fac5bb0641cb879dc8',
    messagingSenderId: '84678725081',
    projectId: 'news-app-ca3a8',
    storageBucket: 'news-app-ca3a8.appspot.com',
    androidClientId: '84678725081-5phl9gcqoehc1rknh7hkggt5o4p8rbtg.apps.googleusercontent.com',
    iosClientId: '84678725081-3vlsbs7d1r5bjibp2vq5i8o2o8hlvr1p.apps.googleusercontent.com',
    iosBundleId: 'com.example.dummyProject1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0OveRe2g_pdcoSXv_LyKqm-7KWAnZyLs',
    appId: '1:84678725081:ios:b692fac5bb0641cb879dc8',
    messagingSenderId: '84678725081',
    projectId: 'news-app-ca3a8',
    storageBucket: 'news-app-ca3a8.appspot.com',
    androidClientId: '84678725081-5phl9gcqoehc1rknh7hkggt5o4p8rbtg.apps.googleusercontent.com',
    iosClientId: '84678725081-3vlsbs7d1r5bjibp2vq5i8o2o8hlvr1p.apps.googleusercontent.com',
    iosBundleId: 'com.example.dummyProject1',
  );
}
