default_platform(:android)

platform :android do
  # desc "Runs all the tests"
  # lane :test do
  #   gradle(task: "test")
  # end

  # desc "Submit a new Beta Build to Crashlytics Beta"
  # lane :beta do
  #   gradle(task: "clean assembleRelease")
  #   crashlytics
  # end

  desc "Testing to run fastlane"
  lane :distribute do
    release = firebase_app_distribution(
      app: "1:84678725081:android:880f24f1e50030a7879dc8",
      # release_note: "Test for release note"
    )
  end
  
end
